[build]
  functions = "netlify/functions"
  publish = "frontend"  # Directory for your static frontend files

[[redirects]]
  from = "/chat"
  to = "/.netlify/functions/chat"
  status = 200
  force = true

[build.environment]
  PYTHON_VERSION = "3.12"