[build]
  functions = "netlify/functions"
  command = "python3 -m pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"  # Netlify has better support for 3.9

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"